Feature/cod 21
hell-coders-tetris/hell-coders-game pull request #13
Opened 2023-05-07 15:55 UTC by tanianova

Вёрстка страницы пользователя — страница с информацией о пользователе(+получение дефолтных значений), возможностью загрузить и сменить аватар, изменить пароль (в попапах), изменить данные о пользователе

![profile](https://user-images.githubusercontent.com/63408388/236688342-fbe950e3-c49b-4c9d-a9c8-11b019945b2e.jpg)

2023-05-07 16:24 UTC, StepanenkoOlgaV approved these changes

2023-05-10 12:48 UTC, Brarion requested changes
Всё хорошо, пару одинаковых замечаний оставил

2023-05-10 12:48 UTC, Brarion commented on packages/client/src/pages/Profile/PasswordPopup/PasswordPopup.tsx
> +export const PasswordPopup: FC<PasswordPopupProps> = ({ open, onClose }) => {
Тип пропсов лучше описывать над самим компонентом и не выносить в отдельный файл

2023-05-10 12:48 UTC, Brarion commented on packages/client/src/pages/Profile/AvatarPopup/AvatarPopup.tsx
> +export const AvatarPopup: FC<AvatarPopupProps> = ({ open, onClose }) => {
Аналогично с типом пропсов

2023-05-10 15:38 UTC, tanianova commented on packages/client/src/pages/Profile/PasswordPopup/PasswordPopup.tsx
> +export const PasswordPopup: FC<PasswordPopupProps> = ({ open, onClose }) => {
исправлено)

2023-05-10 15:38 UTC, tanianova commented on packages/client/src/pages/Profile/AvatarPopup/AvatarPopup.tsx
> +export const AvatarPopup: FC<AvatarPopupProps> = ({ open, onClose }) => {
исправлено)

2023-05-11 17:57 UTC, Brarion approved these changes

2023-05-12 07:39 UTC, merged