Feature/cod 48
hell-coders-tetris/hell-coders-game pull request #34
Opened 2023-06-19 07:14 UTC by StepanenkoOlgaV

### Поддержать API форума на клиенте

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-06-23 06:10 UTC, tanianova approved these changes

2023-06-23 09:47 UTC, Brarion requested changes
Итого:
1. Убрать `.js`, заменить его на `.ts`
2. Убрать `module.export` везде
3. Добавить полную типизацию
4. Изменить `require` на `import`

2023-06-23 09:47 UTC, Brarion commented on packages/client/src/pages/Forum/components/AddReply/AddReply.tsx
> +      id: uuid.v4(),
А разве нужно `id` генерировать на фронте? Обычно этим бек занимается

2023-06-23 09:47 UTC, Brarion commented on packages/client/src/pages/Forum/components/AddTopic/AddTopic.tsx
> +      id: uuid.v4(),
Аналогично

2023-06-23 09:47 UTC, Brarion commented on packages/server/controllers/topic.controller.js
> +    id: req.body.id,
Вот тут как раз `id` приходит с фронта, это не совсем хорошо. При создании фронт просто отдаёт данные без `id`,  а бек уже генерирует `id` (обычно БД этим сама занимается), а возвращается на фронт уже данные + `id`

2023-06-23 09:47 UTC, Brarion commented on packages/server/routes/topic.routes.js
> +};
Начну в этом файле, но нужно будет поменять во всех. Сейчас не очень модно писать `require`, поэтому предлагаю следующее изменение:
```ts
import topics from 'server/controllers/topic.controller'
import { Router } from 'express'

const topicRouter = Router()
  .post('/postTopic', topics.create)
  .get('/topics', topics.findAll)

export default topicRouter

```

Плюс ко всему заметил `.js` файлы, их нужно поменять на `.ts`

2023-06-23 09:47 UTC, Brarion commented on packages/server/controllers/topic.controller.js
> +  const topic = {
В целом по файлу: лучше читаться будет вот так:
```ts
class TopicController {
  static create(req: Типы, res: Типы) {
    // Validate request
    if (!req.body.title) {
      res.status(400).send({
        message: 'Content can not be empty!'
      })
      return
    }

// Create a Topic
    const topic = {
      id: req.body.id,
      title: req.body.title
    }

// Save Topic in the database
    Topic.create(topic)
      .then(data => {
        res.send(data)
      })
      .catch(err => {
        res.status(500).send({
          message:
            err.message || 'Some error occurred while creating the Topic.'
        })
      })

  };
}
```

Лучше конкретные классы/объекты создавать, чем писать `module.export`

2023-06-23 10:09 UTC, StepanenkoOlgaV commented on packages/client/src/pages/Forum/components/AddReply/AddReply.tsx
> +      id: uuid.v4(),
Исправлено

2023-06-23 10:09 UTC, StepanenkoOlgaV commented on packages/client/src/pages/Forum/components/AddTopic/AddTopic.tsx
> +      id: uuid.v4(),
Исправлено везде на проекте

2023-06-23 10:14 UTC, StepanenkoOlgaV commented on packages/server/controllers/topic.controller.js
> +    id: req.body.id,
Заменила

2023-06-23 14:59 UTC, StepanenkoOlgaV commented on packages/server/routes/topic.routes.js
> +};
Исправлено

2023-06-23 15:00 UTC, StepanenkoOlgaV commented on packages/server/controllers/topic.controller.js
> +  const topic = {
Исправлено

2023-06-24 07:14 UTC, Brarion requested changes
Очень маленький совет

2023-06-24 07:14 UTC, Brarion commented on packages/server/controllers/topic.controller.ts
> +    if (!req.body.title) {
Тут `body` надо типизировать
Я для урощения делал вот такую конструкцию когда-то
```ts
import { Request as ExpressRequest } from 'express';

export type Request<
  ReqBody = never,
  ResBody = never,
  ReqQuery = import('express-serve-static-core').Query
> = ExpressRequest<
  import('express-serve-static-core').ParamsDictionary,
  ResBody,
  ReqBody,
  ReqQuery
>;
```

То есть первый аргумент - `body`, второй - возвращаемое значение, а третий - `query`, вродетак попроще чуть-чуть

2023-06-24 07:57 UTC, StepanenkoOlgaV commented on packages/server/controllers/topic.controller.ts
> +    if (!req.body.title) {
Воспользовалась))

2023-06-24 16:00 UTC, Brarion approved these changes
Осталось тип чуть-чуть подправить, в телеге списывались

2023-06-24 23:13 UTC, kkdras commented on packages/server/index.ts
>  createClientAndConnect()
Это наверное можно удалить

2023-06-25 03:58 UTC, StepanenkoOlgaV commented on packages/server/index.ts
>  createClientAndConnect()
да, удалила

2023-06-25 04:01 UTC, merged