Feature/cod 46
hell-coders-tetris/hell-coders-game pull request #37
Opened 2023-06-23 14:14 UTC by tanianova

### [Переключение темы (бэкенд)](https://linear.app/hell-coders/issue/COD-46/pereklyuchenie-temy-bekend)

2023-06-23 14:31 UTC, StepanenkoOlgaV approved these changes

2023-06-23 14:35 UTC, StepanenkoOlgaV approved these changes

2023-06-23 14:53 UTC, kkdras approved these changes

2023-06-24 07:17 UTC, Brarion requested changes
Почти идеально)

2023-06-24 07:17 UTC, Brarion commented on packages/server/controllers/theme.controller.ts
> +  const { userId, theme } = req.body
Тут `body` надо типизировать
Я для урощения делал вот такую конструкцию когда-то
```ts
import { Request as ExpressRequest } from 'express';

export type Request<
  ReqBody = never,
  ResBody = never,
  ReqQuery = import('express-serve-static-core').Query
> = ExpressRequest<
  import('express-serve-static-core').ParamsDictionary,
  ResBody,
  ReqBody,
  ReqQuery
>;
```

То есть первый аргумент - `body`, второй - возвращаемое значение, а третий - `query`, вродетак попроще чуть-чуть

Также валидацию по-хорошему накинуть бы, но это можно потом сделать а рамках рефакторинга, например

2023-06-24 07:17 UTC, Brarion commented on packages/server/routes/theme.routes.ts
> +}
Тут можно просто экспорнуть `themeRoutes`, а `app.use('/api/theme', router)` написать в `index.ts`

2023-06-24 10:02 UTC, tanianova commented on packages/server/routes/theme.routes.ts
> +}
исправлено)

2023-06-24 10:33 UTC, tanianova commented on packages/server/controllers/theme.controller.ts
> +  const { userId, theme } = req.body
добавлены типы IRequestGetTheme, IRequestPostTheme

2023-06-24 16:01 UTC, Brarion approved these changes
Тоже отличное решение, даже красивее получилось, супер)

2023-06-24 16:51 UTC, merged